server:
  port: 8000
  servlet:
    context-path: /gateway


spring:
  #redis集群
  redis:
    host: 192.168.248.129
    port: 6379
    timeout: 20000s
    #    集群环境打开下面注释，单机不需要打开
    #    cluster:
    #      集群信息
    #      nodes: xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx
    #      #默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
    #      maxRedirects: 3
    password:
    application:
      name: test
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1
    database: 0

  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
      # jdbc_config
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.248.129:3306/cloud?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      # Hikari
      type: com.zaxxer.hikari.HikariDataSource

  cloud:
    gateway:
      routes:
        -id: url-proxy-1
          uri: https://localhost:8787
          predicates:
            -Path=/cloud