server:
  port: 9527

spring:
  application:
    name: gateway-admin
  cloud:
    gateway:
      routes:
        - id: gateway-web
#          uri: http://localhost:9010
          uri: lb://gateway-web
          predicates:
            - Path=/gateway/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka