server:
  port: 80

spring:
  application:
    name: api-client

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
logging:
  level:
    root: info
    com.eg: debug